[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildTarget = "production"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/health/"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
