# Generated by Django 4.2.30 on 2026-05-30 23:28

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("couriers", "0001_initial"),
        ("fleet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("pickup_address", models.TextField()),
                (
                    "pickup_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("pickup_contact_name", models.CharField(blank=True, max_length=100)),
                ("pickup_contact_phone", models.CharField(blank=True, max_length=20)),
                ("pickup_instructions", models.TextField(blank=True)),
                ("delivery_address", models.TextField()),
                (
                    "delivery_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("delivery_contact_name", models.CharField(blank=True, max_length=100)),
                ("delivery_contact_phone", models.CharField(blank=True, max_length=20)),
                ("delivery_instructions", models.TextField(blank=True)),
                ("package_description", models.TextField(blank=True)),
                ("package_size", models.CharField(default="small", max_length=10)),
                ("is_fragile", models.BooleanField(default=False)),
                (
                    "estimated_weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de coursier"),
                            ("accepted", "Acceptée"),
                            ("pickup", "En route vers le départ"),
                            ("in_progress", "En cours"),
                            ("delivered", "Livrée"),
                            ("cancelled", "Annulée"),
                            ("failed", "Échouée"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("client_request", "Annulation client"),
                            ("courier_unavailable", "Coursier indisponible"),
                            ("address_issue", "Problème d'adresse"),
                            ("payment_failed", "Paiement échoué"),
                            ("other", "Autre"),
                        ],
                        max_length=30,
                    ),
                ),
                ("cancellation_note", models.TextField(blank=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("picked_up_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("client_review", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_requests",
                        to="couriers.courier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de livraison",
                "verbose_name_plural": "Demandes de livraison",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="services_se_status_8f0b00_idx",
                    ),
                    models.Index(
                        fields=["client", "status"],
                        name="services_se_client__2c6fb0_idx",
                    ),
                    models.Index(
                        fields=["courier", "status"],
                        name="services_se_courier_eca524_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RideRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("pickup_address", models.TextField()),
                (
                    "pickup_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("dropoff_address", models.TextField()),
                (
                    "dropoff_location",
                    django.contrib.gis.db.models.fields.PointField(srid=4326),
                ),
                ("passenger_count", models.PositiveSmallIntegerField(default=1)),
                (
                    "client_has_own_vehicle",
                    models.BooleanField(
                        default=False,
                        help_text="True si le client a son propre véhicule et cherche un chauffeur",
                    ),
                ),
                ("special_instructions", models.TextField(blank=True)),
                (
                    "estimated_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de chauffeur"),
                            ("accepted", "Acceptée"),
                            ("driver_arriving", "Chauffeur en route"),
                            ("in_progress", "Course en cours"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client_rating",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("client_review", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "client"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ride_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ride_requests",
                        to="drivers.driver",
                    ),
                ),
                (
                    "fleet_rental",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ride_requests",
                        to="fleet.vehiclerental",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de course",
                "verbose_name_plural": "Demandes de course",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="services_ri_status_310f41_idx",
                    ),
                    models.Index(
                        fields=["client", "status"],
                        name="services_ri_client__3f7b75_idx",
                    ),
                    models.Index(
                        fields=["driver", "status"],
                        name="services_ri_driver__23146d_idx",
                    ),
                ],
            },
        ),
    ]
