# Generated by Django 4.2.30 on 2026-05-30 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("fleet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_earned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total_withdrawn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("currency", models.CharField(default="XOF", max_length=5)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Portefeuille",
            },
        ),
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe (Carte bancaire)"),
                            ("orange_money", "Orange Money"),
                            ("wave", "Wave"),
                            ("cash", "Espèces"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvée"),
                            ("rejected", "Rejetée"),
                            ("paid", "Payée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="payments.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de retrait",
                "verbose_name_plural": "Demandes de retrait",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe (Carte bancaire)"),
                            ("orange_money", "Orange Money"),
                            ("wave", "Wave"),
                            ("cash", "Espèces"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("service_delivery", "Livraison de colis"),
                            ("ride", "Course / Transport"),
                            ("rental", "Location de véhicule"),
                            ("deposit", "Caution"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Complété"),
                            ("failed", "Échoué"),
                            ("refunded", "Remboursé"),
                            ("cancelled", "Annulé"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="XOF", max_length=5)),
                (
                    "reference",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(blank=True, max_length=200),
                ),
                ("provider_response", models.JSONField(blank=True, null=True)),
                ("initiated_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rental",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction",
                        to="fleet.vehiclerental",
                    ),
                ),
                (
                    "ride_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction",
                        to="services.riderequest",
                    ),
                ),
                (
                    "service_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction",
                        to="services.servicerequest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "status"],
                        name="payments_tr_client__52875c_idx",
                    ),
                    models.Index(
                        fields=["provider", "status"],
                        name="payments_tr_provide_cb836c_idx",
                    ),
                ],
            },
        ),
    ]
