# Generated by Django 4.2.30 on 2026-05-30 23:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de validation"),
                            ("active", "Actif"),
                            ("suspended", "Suspendu"),
                            ("online", "En ligne"),
                            ("offline", "Hors ligne"),
                            ("busy", "En course"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("vehicle_plate", models.CharField(max_length=20, unique=True)),
                ("vehicle_model", models.CharField(max_length=100)),
                (
                    "vehicle_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("vehicle_color", models.CharField(blank=True, max_length=50)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "last_known_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("total_trips", models.PositiveIntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_available", models.BooleanField(db_index=True, default=False)),
                (
                    "max_package_size",
                    models.CharField(
                        choices=[
                            ("small", "Petit (< 5kg)"),
                            ("medium", "Moyen (5-20kg)"),
                            ("large", "Grand (20-50kg)"),
                            ("xl", "Très grand (> 50kg)"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("accepts_fragile", models.BooleanField(default=True)),
                ("accepts_documents", models.BooleanField(default=True)),
                (
                    "delivery_zone_radius_km",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Rayon max de livraison en km depuis la position actuelle",
                    ),
                ),
                ("service_area", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "Coursier",
                "verbose_name_plural": "Coursiers",
            },
        ),
        migrations.CreateModel(
            name="CourierEarning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to="couriers.courier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gain coursier",
                "verbose_name_plural": "Gains coursiers",
                "ordering": ["-earned_at"],
            },
        ),
    ]
