# Generated by Django 4.2.30 on 2026-05-30 23:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de validation"),
                            ("active", "Actif"),
                            ("suspended", "Suspendu"),
                            ("online", "En ligne"),
                            ("offline", "Hors ligne"),
                            ("busy", "En course"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("vehicle_plate", models.CharField(max_length=20, unique=True)),
                ("vehicle_model", models.CharField(max_length=100)),
                (
                    "vehicle_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("vehicle_color", models.CharField(blank=True, max_length=50)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                (
                    "last_known_location",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("total_trips", models.PositiveIntegerField(default=0)),
                (
                    "total_earnings",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("is_available", models.BooleanField(db_index=True, default=False)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("chauffeur_only", "Chauffeur seul (client avec véhicule)"),
                            (
                                "vehicle_with_driver",
                                "Véhicule + Chauffeur (location avec chauffeur)",
                            ),
                            ("both", "Les deux"),
                        ],
                        default="both",
                        max_length=30,
                    ),
                ),
                (
                    "vehicle_category",
                    models.CharField(
                        choices=[
                            ("moto", "Moto-taxi"),
                            ("tricycle", "Tricycle"),
                            ("car", "Voiture"),
                            ("minibus", "Minibus"),
                            ("van", "Van/Fourgonnette"),
                        ],
                        default="moto",
                        max_length=20,
                    ),
                ),
                ("passenger_capacity", models.PositiveSmallIntegerField(default=1)),
                (
                    "owns_vehicle",
                    models.BooleanField(
                        default=False,
                        help_text="True si le chauffeur possède son propre véhicule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chauffeur",
                "verbose_name_plural": "Chauffeurs",
            },
        ),
        migrations.CreateModel(
            name="DriverEarning",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commission_rate",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earnings",
                        to="drivers.driver",
                    ),
                ),
            ],
            options={
                "verbose_name": "Gain chauffeur",
                "verbose_name_plural": "Gains chauffeurs",
                "ordering": ["-earned_at"],
            },
        ),
    ]
