# Generated by Django 4.2.30 on 2026-05-30 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0001_initial"),
        ("disputes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dispute",
            name="ride_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disputes",
                to="services.riderequest",
            ),
        ),
        migrations.AddField(
            model_name="dispute",
            name="service_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disputes",
                to="services.servicerequest",
            ),
        ),
    ]
