# Generated by Django 4.2.30 on 2026-05-30 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("moto", "Moto"),
                            ("tricycle", "Tricycle"),
                            ("car", "Voiture"),
                            ("minibus", "Minibus"),
                            ("van", "Van"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.PositiveSmallIntegerField()),
                ("color", models.CharField(max_length=50)),
                ("plate_number", models.CharField(max_length=20, unique=True)),
                (
                    "chassis_number",
                    models.CharField(blank=True, max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Disponible"),
                            ("rented", "En location"),
                            ("maintenance", "En maintenance"),
                            ("inactive", "Inactif"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("passenger_capacity", models.PositiveSmallIntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="fleet/vehicles/"
                    ),
                ),
                ("requires_driver", models.BooleanField(default=False)),
                ("mileage_km", models.PositiveIntegerField(default=0)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("registration_expiry", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Véhicule",
                "verbose_name_plural": "Véhicules",
                "ordering": ["vehicle_type", "brand"],
            },
        ),
        migrations.CreateModel(
            name="VehicleRental",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("active", "En cours"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("with_driver", models.BooleanField(default=False)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("actual_end_date", models.DateTimeField(blank=True, null=True)),
                ("pickup_location", models.TextField(blank=True)),
                ("dropoff_location", models.TextField(blank=True)),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("deposit_returned", models.BooleanField(default=False)),
                ("client_notes", models.TextField(blank=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optionnel: chauffeur assigné pour conduire le véhicule loué",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rentals",
                        to="drivers.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rentals",
                        to="fleet.vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Location de véhicule",
                "verbose_name_plural": "Locations de véhicules",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "start_date"],
                        name="fleet_vehic_status_fc0a80_idx",
                    )
                ],
            },
        ),
    ]
