# Generated by Django 4.2.30 on 2026-05-30 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("service_accepted", "Livraison acceptée"),
                            ("service_pickup", "Coursier en route"),
                            ("service_in_progress", "Livraison en cours"),
                            ("service_delivered", "Livraison effectuée"),
                            ("service_cancelled", "Livraison annulée"),
                            ("ride_accepted", "Course acceptée"),
                            ("ride_driver_arriving", "Chauffeur en route"),
                            ("ride_started", "Course démarrée"),
                            ("ride_completed", "Course terminée"),
                            ("payment_success", "Paiement réussi"),
                            ("payment_failed", "Paiement échoué"),
                            ("new_request_nearby", "Nouvelle demande à proximité"),
                            ("dispute_update", "Mise à jour litige"),
                            ("system", "Notification système"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField()),
                ("data", models.JSONField(blank=True, null=True)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("sent_push", models.BooleanField(default=False)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "created_at"],
                        name="notificatio_recipie_86ea8b_idx",
                    )
                ],
            },
        ),
    ]
